$(document).ready(function(){
  $('.skill').removeClass('underline');
  $('.skill').mouseenter(function(){
    $(this).addClass('underline');
  });
  $('.skill').mouseleave(function(){
    $(this).removeClass('underline');
  });
});
